### ISSUE TITLE
Add low level logging of written #{records} to out_kinesis_streams.rb

### ISSUE THREAD

**Issue by mi5c** [awslabs/aws-fluent-plugin-kinesis#105]
While creating the kinesis integration it would be helpful to see what was actually written out from the host.

At the moment I can see that x amount of records were written:
```
2017-02-07 03:54:07 -0800 [debug]: plugin/out_kinesis_streams.rb:29:write: Written 6 records
```
.. and I  can see that some of the lines did not match the format I specified:
```
2017-02-07 03:45:14 -0800 [warn]: plugin/in_tail.rb:276:block in convert_line_to_event: pattern not match: <my pattern>
```
What i do not see is what actually matched and how it eventually looked.

Possilble solution:
Line 28 debugs:
```
      log.debug("Written #{records.size} records")
```
I would suggest adding
```
      log.debug("Written #{records}") after line 28.
```
Too bad ruby does not have lower level logging than debug, I'd say this is suitable for `log.trace` call.

Referenced file and line: 

https://github.com/awslabs/aws-fluent-plugin-kinesis/blob/master/lib/fluent/plugin/out_kinesis_streams.rb#L28

**Comment by riywo** [comment]
Hi @mi5c ,

Thank you for creating this issue. I'm sorry for my late reply.

Sometime records are huge so that output of whole records will be too much information. Because of that, I don't think expanding records to debug log is the best solution for you.

I think you can dispatch in_tail warn message using fluentd config. Maybe `<match fluent.**>`.

I'd like to close this but if you have any more comment, feel free to add comment here.

Best,

**Comment by mi5c** [comment]
Fair enough.

I used the approach I described to do the initial migration, later I switched the logging level back to info. 
It was useful for me to see the matched messages on the host already, since the final repository for storing the log entries was not ready for me.
