### ISSUE TITLE
When using shared_credentials, plugin does not seem to honor session token expiry

### ISSUE THREAD

**Issue by wltbenade** [awslabs/aws-fluent-plugin-kinesis#217]
Hi guys,

We've encountered an issue when configuring the plugin with rotating credentials via shared_credentials. Regardless of the duration of the session token, once it has rotated in the credentials file, the plugin does not seem to read the new configuration.

It should be noted that delivery works as expected whilst the session token is valid.
Plugin version:
~~~
fluent-plugin-kinesis (3.4.2)
~~~

Plugin config:
~~~xml
<match **>
  @type kinesis_streams
  stream_name "#{ENV['STREAM_NAME']}"
  <shared_credentials>
     path             /root/.aws/credentials
     profile_name     default
   </shared_credentials>
   <buffer>
    @type file
    path /var/log/fluentd-buffers/kubernetes.system.buffer
    flush_mode interval
    retry_type exponential_backoff
    flush_thread_count 2
    flush_interval 5s
    retry_forever
    retry_max_interval 30
    overflow_action block
    </buffer>
</match>
~~~

$HOME/.aws/credentials:
~~~
[default]
aws_access_key_id        = REDACTED
aws_secret_access_key    = REDACTED
aws_session_token        = REDACTED
aws_security_token       = REDACTED
x_principal_arn          = REDACTED 
x_security_token_expires = 2021-12-24T13:11:46Z
region                   = eu-west-1
~~~

Error from Fleuntd:
> [warn]: #0 failed to flush the buffer. retry_times=12 next_retry_time=2021-12-24 12:25:14 +0000 chunk="5d3e3629e9bfb3ae2941e5c2a3a622f6" error_class=Aws::Kinesis::Errors::ExpiredTokenException error="The security token included in the request is expired"

Would it be possible to implement duration_seconds on shared_credentials in a similar fashion as it works on `assume_role_credentials`?

Cheers!

**Comment by simukappu** [comment]
Hi @wltbenade, thank you for your feedback.

This plugin uses AWS SDK for Ruby v3 as it is. AWS SDK for Ruby credential providers (including assume role credentials) already provide [refreshable credentials](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/refreshing_credentials.rb), which are intended for auto-refresh when expired. Please see this [related issue](https://github.com/aws/aws-sdk-ruby/issues/2097).
However, this auto-refresh doesn't seem to work for *Aws::Kinesis::Errors::ExpiredTokenException* since retry errors does not include 'ExpiredTokenException' [here](https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retries/error_inspector.rb#L9-L18). If you would like to add auto-refresh working with Kinesis, I think this should be handled in AWS SDK side.
What do you think about it? Can you provide an enhancement request to AWS SDK for Ruby?

**Comment by wltbenade** [comment]
Hi @simukappu, 

Happy New Year to you and the team!

Thanks for the suggestions! Just to be clear on your recommendation:

1. The ErrorInspector class in error_inspector.rb should be expanded to include ExpiredTokenException, as well as ExpiredToken.
2. A proper result from the ErrorInspector class in error_inspector.rb will result in the plugin reloading the credentials from disk again?

Another thought just occurred to me. The credentials on disk are rotated prior to their expiry. Would it not be more pertinent to reload them upon detecting a refresh?

**Comment by wltbenade** [comment]
Hi @simukappu,

Any update on my question above?

Cheers

**Comment by simukappu** [comment]
Hi @wltbenade

Sorry for my late reply. Thank you for your enhancement request to AWS SDK for Ruby. Could you check if this issue would be resolved with this plugin? You have to use the latest AWS SDK for Ruby, not included version in td-agent.

**Comment by divbasson2** [comment]
Hi, any feedback on the comment posted by @wltbenade above?

**Comment by simukappu** [comment]
Is anyone who has the same issue with latest AWS SDK for Ruby? If not, we'll close the issue for now.
