### ISSUE TITLE
error_class=Encoding::UndefinedConversionError error="\"\\xC2\" from ASCII-8BIT to UTF-8" 

### ISSUE THREAD

**Issue by nlawson** [awslabs/aws-fluent-plugin-kinesis#34]
Hello, 

Im having an issue only when I'm using the kinsis plugin with my logs,  I'm messages in my logs " error="\"\\xC2\" from ASCII-8BIT to UTF-8" 

```
<source>
  force_encoding('UTF-8')
  type  tail
  format  json
  path  /to/some/file
  tag  somelog
  pos_file /some/position/file.whatever
</source>

<match **>
  type kinesis
  random_partition_key
  aws_key_id xxxxxx
  aws_sec_key xxxxxxxx
  region us-east-1
  stream_name xxxxx
  flush_interval 
</match>
```
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
aws-sdk-core (2.1.28)
bigdecimal (1.2.6)
cool.io (1.4.1)
fluent-plugin-kinesis (0.3.6)
fluentd (0.12.16)
http_parser.rb (0.6.0)
io-console (0.4.3)
jmespath (1.1.3)
json (1.8.1)
minitest (5.4.3)
msgpack (0.5.12)
multi_json (1.11.2)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
sigdump (0.2.3)
string-scrub (0.0.5)
test-unit (3.0.8)
thread_safe (0.3.5)
tzinfo (1.2.2)
tzinfo-data (1.2015.7)
yajl-ruby (1.2.1)

any help or suggestions would be appreciated.

**Comment by imaifactory** [comment]
@nlawson 

Hi, at this point of time, I'm not sure this error is from in_tail plugin or out_kinesis plugin. Can you try [stdout Output Plugin](http://docs.fluentd.org/articles/out_stdout) instead of kinesis plugin, to address where the problem is.

Also please try using [use_yajl](https://github.com/awslabs/aws-fluent-plugin-kinesis#use_yajl) for kinesis plugin.

If problem is not addressed with above, please paste your full error messages here.

Thanks!

**Comment by nlawson** [comment]
I did try the std out plugin, and the error did not occur. so I'm sure it's something with the kinesis plugin., but ill try the use_yajl

**Comment by wryun** [comment]
I have also seen this.

**Comment by nlawson** [comment]
@imaifactory Thanks!, this seems to addressed my issues, how if i can get our dev's to quit logging messages larger than 200kb in size (facepalm).....
