### ISSUE TITLE
Http_proxy

### ISSUE THREAD

**Issue by iamhasibrahman** [awslabs/aws-fluent-plugin-kinesis#48]
Can I use IP instead of DNS as our internet network doesn't allow name?

**Comment by riywo** [comment]
Hi @iamhasibrahman ,

Did you try it and got some errors? If so, could you paste the errors?

**Comment by iamhasibrahman** [comment]
Wow, you finally replied man!!!!! Not error. On the document it says http prxoy has to be in DNS format, which we don't support. I mean our internal networking doesn't allow resolving DNS host. So you are saying IP would work? Also, from source to proxy, data is sent via SSL?

**Comment by riywo** [comment]
Although I didn't test it, it could be a general URL including IP address because it is just passed to AWS SDK and Net::Http. See http://ruby-doc.org/stdlib-2.3.0/libdoc/net/http/rdoc/Net/HTTP.html#method-c-new

For SSL, I think it is encrypted. See http://stackoverflow.com/questions/516323/https-connections-over-proxy-servers

If you have any error, please reopen this.

**Comment by iamhasibrahman** [comment]
I've one very key yet simple question - this part of code (connecting via proxy) is part of KPL or the code you had to write?

**Comment by riywo** [comment]
Are you asking about `kinesis_producer` of v1.0.0? In that case, there is no option called `http_proxy` because KPL doesn't support it.

If you ask about  v0.4.0, or `kinesis_streams` or `kinesis_firehose` of v1.0.0, it is a part of code in AWS SDK for Ruby using Net::HTTP in stdlib.

**Comment by iamhasibrahman** [comment]
I'm asking about your plugin - https://github.com/awslabs/aws-fluent-plugin-kinesis
It supports proxy, right? If not, Houston we got a huge problem !!

**Comment by riywo** [comment]
See https://github.com/awslabs/aws-fluent-plugin-kinesis/issues/51
