### ISSUE TITLE
fluentd agent and plugin

### ISSUE THREAD

**Issue by iamhasibrahman** [awslabs/aws-fluent-plugin-kinesis#51]
Hi, 

Referring to your previous answer around supporting http_proxy. 

There might be a confusion here, so let me clarify. 

First, our assumption was was-fluent-plugin-kinesis is based on KPL, that's why we asked whether this http_proxy is part of KPL code. 

Second, let me tell you how we think of deploying - 

1. fluentd agent to collect data
2. and your plugin to send data to kinesis stream
3. And we'll have a proxy in between. 

So the question is, if we use your plugin, the proxy is supported. And the second question is, your plugin is based on KPL or actually it's written on AWS SDK for Ruby. If that's the case, do we need to have both Java (1.7) and Ruby Interpretor on the source system for your agent to run?

Please let us know. 

Thanks.

**Comment by riywo** [comment]
Sorry for the confusing documentation. I'm going to explain about your questions.

First, this plugin is originally based on AWS SDK for Ruby only because it was released before KPL launched. Second, AWS SDK for Ruby has `http_proxy` feature and this plugin supports that option. So, this plugin supports `http_proxy` like this in v0.4.0:

    @type kinesis
    http_proxy http://user:pass@host_or_ip

Now, I'm developing the new version v1.0.0. It will add an option to use KPL. It runs with a Ruby wrapper developed by me, without any Java dependency. Unfortunately, KPL itself does not support `http_proxy` so far, this option doesn't support it neither. Still there is AWS SDK for Ruby version in v1.0.0, you can use `http_proxy` with it:

    @type kinesis_streams
    http_proxy http://user:pass@host_or_ip

Here is the comparison matrix:

| version | plugin type | based on | support `http_proxy`? |
|---------|---------|-----------|----------------------------|
| v0.4.0| `kinesis` | AWS SDK for Ruby | yes |
| v1.0.0| `kinesis_streams` | AWS SDK for Ruby | yes |
| v1.0.0| `kinesis_producer` | KPL | no |

**Comment by iamhasibrahman** [comment]
this plugin is kinesis version - 0.4.0 ......KPL is 1.0 - which we can ignore for a moment. Kinesis_Stream plugin - is that something else you are designing or finished and available already? 

On a different note, is your plugin supporting batch upload?

**Comment by riywo** [comment]
v1.0.0 is available on [GitHub v1.0 branch of this repo](https://github.com/awslabs/aws-fluent-plugin-kinesis/tree/v1.0) and [rubygems prerelease](https://rubygems.org/gems/fluent-plugin-kinesis/versions/1.0.0.rc9). See also https://github.com/awslabs/aws-fluent-plugin-kinesis/pull/46 .

Both v0.4.0 and v1.0.0 support batch upload, called PutRecords API.

**Comment by auziel** [comment]
@riywo Does the following is a valid URL:

@type kinesis_streams
http_proxy http://user:pass@host_or_ip:port

can it be that a # sign in the password string will be problematic?
