### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by iamhasibrahman** [awslabs/aws-fluent-plugin-kinesis#61]
The format suggested for http_proxy didn't work.

So the below is not working - 

http_proxy http://user:password@172.17.100.181:9090

This format seemed to work 

http_proxy user:password@host:port

**Comment by riywo** [comment]
Please attach the error output.

**Comment by iamhasibrahman** [comment]
Since it was working with the second format, don't have any logs...

**Comment by riywo** [comment]
Is there any output when you tried http://user:password@172.17.100.181:9090?

**Comment by iamhasibrahman** [comment]
Check this out .. The SSL thing. 

I’ve explicitly specified a trusted certificate .pem in the VM: touch /etc/sysconfig/td-agent # This file is sourced by /bin/sh from /etc/init.d/td-agent# Options to pass to td-agentexport SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem Also commented out #TD_AGENT_OPTIONS="--use-v1-config" in /etc/init.d/td-agent No longer seeing SSL errors in the logs. 
--
{...Hasib +61 432 745 136)




On Mon, Mar 28, 2016 at 11:36 PM -0700, "Ryosuke IWANAGA" <notifications@github.com> wrote:












Is there any output when you tried http://user:password@172.17.100.181:9090?

**Comment by riywo** [comment]
`user:password@172.17.100.181:9090` format is not http URI so that Ruby SDK doesn't use the proxy, which means the direct internet connection to Kinesis API.

You must `http://user:password@172.17.100.181:9090` format if you want to use http proxy.

**Comment by riywo** [comment]
Ruby SDK sends messages below to your proxy, then starts the tunnel mode to communicate with Kinesis API.

https://github.com/ruby/ruby/blob/ec0198fd8cfee7ae499602235fcf3a9318f9b691/lib/net/http.rb#L912-L918
````ruby
buf = "CONNECT #{@address}:#{@port} HTTP/#{HTTPVersion}\r\n"
buf << "Host: #{@address}:#{@port}\r\n"
if proxy_user
  credential = ["#{proxy_user}:#{proxy_pass}"].pack('m0')
  buf << "Proxy-Authorization: Basic #{credential}\r\n"
end
buf << "\r\n"
````

If your proxy doesn't support CONNECT method, it will fail. If you want to connect your proxy with your SSL cert at first, you can use `http_proxy https://user:pass@host:port` (note: https instead of http), I guess, but no guarantee because it is hard to setup such environment by myself.

**Comment by riywo** [comment]
Close since I heard there is no issue now.
