### ISSUE TITLE
Plugin incompatible with new fluentd release 0.14

### ISSUE THREAD

**Issue by comtef** [awslabs/aws-fluent-plugin-kinesis#70]
The kinesis plugin is not compatible with the new release of fluentd (0.14).
Startup fail with the following message :

> 2016-06-01 09:37:04 +0000 [error]: unexpected error error="uninitialized constant Fluent::DetachMultiProcessMixin"
>   2016-06-01 09:37:04 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-kinesis-1.0.1/lib/fluent/plugin/kinesis_helper.rb:23:in `<module:KinesisHelper>'

The use of detach_process in an output plugin was pointed as a bad practice from fluentd developper tagomoris and will be deprecated in future release.

> output plugins using detach_process looks very curious from viewpoint of fluentd core developer...

**Comment by riywo** [comment]
Hi @comtef ,

Thank you for reporting. I think some `require` statements has been got rid of in v0.14 so that this plugin is facing the missing of module. I'll fix it soon.

To stop using detach_process in this plugin, we need more investigation to get high throughput with a thread model in MRI. This is a separate topic for this issue. I'll open an issue.

**Comment by riywo** [comment]
Hi @comtef ,

I've released v1.1.0 to fix this issue and more. Please check it out and let me know if anything.
https://rubygems.org/gems/fluent-plugin-kinesis/versions/1.1.0
